import type {
  APBDesa,
  AIPrediction,
  Announcement,
  Article,
  Comment,
  CommunityAction,
  DashboardStats,
  GalleryItem,
  HealthScore,
  Job,
  Product,
  Project,
  Report,
  ReportHistory,
  TrainingModule,
} from '@/lib/types';
import type { AppSettings } from '@/lib/map-settings';
import type { AuthUser } from '@/lib/auth';

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/photo-${id}?q=80&w=${w}&auto=format&fit=crop`;

export const STATIC_APP_SETTINGS: AppSettings = {
  village_name: 'Labuhan Maringgai',
  district_name: 'Labuhan Maringgai',
  city_name: 'Lampung Timur',
  province_name: 'Lampung',
  center_lat: -5.3428912,
  center_lng: 105.7938069,
  boundary_geojson: [
    [
      [105.750, -5.310],
      [105.805, -5.320],
      [105.820, -5.350],
      [105.800, -5.365],
      [105.760, -5.355],
      [105.750, -5.310],
    ],
  ],
  fallback_radius_m: 2500,
};

export const STATIC_REPORTS: Report[] = [
  {
    id: 'report-1',
    user_id: 'user-warga',
    author_name: 'Budi Santoso',
    title: 'Jalan berlubang di RT 02',
    description: 'Lubang besar di Jalan Melati dekat balai desa sangat membahayakan pengendara motor terutama saat malam hari.',
    category: 'Infrastruktur',
    status: 'in_progress',
    lat: -5.3429,
    lng: 105.7938,
    image_url: img('1515162816999-a0c47dc192f7'),
    upvotes: 12,
    comments_count: 2,
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'report-2',
    user_id: 'user-warga',
    author_name: 'Siti Aminah',
    title: 'Tumpukan sampah di pasar',
    description: 'Sampah menumpuk di belakang pasar desa sudah 3 hari belum diangkut, menimbulkan bau tidak sedap.',
    category: 'Sampah',
    status: 'pending',
    lat: -5.344,
    lng: 105.795,
    image_url: img('1558618666-fcd25c85cd64'),
    upvotes: 8,
    comments_count: 1,
    created_at: '2026-05-31T08:00:00.000Z',
  },
  {
    id: 'report-3',
    user_id: 'user-warga',
    author_name: 'Andi Pratama',
    title: 'Lampu jalan mati di gang utama',
    description: 'Lampu penerangan jalan umum di gang utama RW 03 mati total, rawan tindak kejahatan.',
    category: 'Keamanan',
    status: 'completed',
    lat: -5.341,
    lng: 105.792,
    image_url: img('1542315192-1f61a1792f33'),
    upvotes: 20,
    comments_count: 1,
    created_at: '2026-05-20T08:00:00.000Z',
  },
  {
    id: 'report-4',
    user_id: 'user-warga',
    author_name: 'Dewi Lestari',
    title: 'Saluran irigasi tersumbat',
    description: 'Saluran irigasi sawah tersumbat sampah dan lumpur, air tidak mengalir ke area persawahan warga.',
    category: 'Lingkungan',
    status: 'pending',
    lat: -5.345,
    lng: 105.796,
    image_url: img('1500382017468-9049fed747ef'),
    upvotes: 5,
    comments_count: 0,
    created_at: '2026-06-02T08:00:00.000Z',
  },
  {
    id: 'report-5',
    user_id: 'user-warga',
    author_name: 'Rahmat Hidayat',
    title: 'Posyandu butuh perlengkapan',
    description: 'Posyandu Melati kekurangan timbangan bayi dan alat ukur tinggi badan untuk kegiatan rutin bulanan.',
    category: 'Kesehatan',
    status: 'in_progress',
    lat: -5.3435,
    lng: 105.7945,
    image_url: img('1576091160550-2173dba999ef'),
    upvotes: 15,
    comments_count: 1,
    created_at: '2026-05-27T08:00:00.000Z',
  },
];

export const STATIC_REPORT_COMMENTS: Comment[] = [
  { id: 'comment-1', report_id: 'report-1', author_name: 'Admin Desa', content: 'Tim sudah menjadwalkan survei lokasi.', created_at: '2026-05-30T09:00:00.000Z' },
  { id: 'comment-2', report_id: 'report-1', author_name: 'Warga', content: 'Mohon dipasang tanda sementara karena cukup berbahaya.', created_at: '2026-05-30T13:00:00.000Z' },
  { id: 'comment-3', report_id: 'report-2', author_name: 'Petugas Kebersihan', content: 'Pengangkutan tambahan dijadwalkan sore ini.', created_at: '2026-06-01T08:30:00.000Z' },
  { id: 'comment-4', report_id: 'report-3', author_name: 'Admin Desa', content: 'Lampu sudah diperbaiki dan menyala normal.', created_at: '2026-05-22T10:00:00.000Z' },
  { id: 'comment-5', report_id: 'report-5', author_name: 'Kader Posyandu', content: 'Daftar kebutuhan sudah kami teruskan ke perangkat desa.', created_at: '2026-05-28T11:00:00.000Z' },
];

export const STATIC_REPORT_HISTORY: ReportHistory[] = [
  { id: 'hist-1', report_id: 'report-1', status: 'pending', note: 'Laporan masuk dan menunggu verifikasi.', changed_by: 'Sistem', created_at: '2026-05-29T08:00:00.000Z' },
  { id: 'hist-2', report_id: 'report-1', status: 'in_progress', note: 'Tim teknis dijadwalkan melakukan survei.', changed_by: 'Admin Desa', created_at: '2026-05-30T08:00:00.000Z' },
  { id: 'hist-3', report_id: 'report-3', status: 'pending', note: 'Laporan diterima.', changed_by: 'Sistem', created_at: '2026-05-20T08:00:00.000Z' },
  { id: 'hist-4', report_id: 'report-3', status: 'completed', note: 'Lampu jalan selesai diperbaiki.', changed_by: 'Admin Desa', created_at: '2026-05-22T10:00:00.000Z' },
];

export const STATIC_STORES = [
  {
    id: 'store-1',
    user_id: 'demo-admin',
    name: 'Warung Bu Sari',
    description: 'Produk makanan ringan rumahan dari bahan lokal desa.',
    address: 'Jl. Melati No. 12, Labuhan Maringgai',
    logo_url: img('1542838132-92c53300491e', 300),
    status: 'active',
    created_at: '2026-01-14T08:00:00.000Z',
  },
  {
    id: 'store-2',
    user_id: 'seller-2',
    name: 'Kriya Bambu Maringgai',
    description: 'Kerajinan bambu dan anyaman untuk kebutuhan rumah tangga.',
    address: 'Dusun Sukamaju, Lampung Timur',
    logo_url: img('1513519245088-0e12902e35ca', 300),
    status: 'active',
    created_at: '2026-02-02T08:00:00.000Z',
  },
  {
    id: 'store-3',
    user_id: 'seller-3',
    name: 'Tani Segar Desa',
    description: 'Hasil panen segar langsung dari petani lokal.',
    address: 'Area Pasar Desa Labuhan Maringgai',
    logo_url: img('1500937386664-56d1dfef3854', 300),
    status: 'active',
    created_at: '2026-03-05T08:00:00.000Z',
  },
];

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'product-1',
    user_id: 'demo-admin',
    store_id: 'store-1',
    seller_name: 'Warung Bu Sari',
    name: 'Keripik Pisang Manis',
    description: 'Keripik pisang renyah dengan rasa manis gurih, cocok untuk camilan keluarga.',
    price: 18000,
    phone_number: '6281234567890',
    whatsapp: '6281234567890',
    image_url: img('1558961363-fa8fdf82db35'),
    category: 'Makanan',
    stock: 48,
    featured: true,
    sales_count: 124,
    rating: 4.8,
    reviews_count: 18,
    created_at: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'product-2',
    user_id: 'seller-2',
    store_id: 'store-2',
    seller_name: 'Kriya Bambu Maringgai',
    name: 'Besek Bambu Handmade',
    description: 'Besek bambu kuat dan rapi untuk hantaran, kemasan makanan, atau dekorasi.',
    price: 12000,
    phone_number: '6281122334455',
    whatsapp: '6281122334455',
    image_url: img('1513519245088-0e12902e35ca'),
    category: 'Kerajinan',
    stock: 80,
    featured: true,
    sales_count: 76,
    rating: 4.7,
    reviews_count: 11,
    created_at: '2026-04-12T08:00:00.000Z',
  },
  {
    id: 'product-3',
    user_id: 'seller-3',
    store_id: 'store-3',
    seller_name: 'Tani Segar Desa',
    name: 'Sayur Organik Pakcoy',
    description: 'Pakcoy segar tanpa pestisida berat, dipanen pagi hari.',
    price: 9000,
    phone_number: '6285566778899',
    whatsapp: '6285566778899',
    image_url: img('1518977676601-b53f82aba655'),
    category: 'Pertanian',
    stock: 35,
    featured: false,
    sales_count: 58,
    rating: 4.6,
    reviews_count: 7,
    created_at: '2026-04-18T08:00:00.000Z',
  },
  {
    id: 'product-4',
    user_id: 'demo-admin',
    store_id: 'store-1',
    seller_name: 'Warung Bu Sari',
    name: 'Sambal Terasi Rumahan',
    description: 'Sambal terasi pedas harum dalam kemasan botol higienis.',
    price: 22000,
    phone_number: '6281234567890',
    whatsapp: '6281234567890',
    image_url: img('1504674900247-0877df9cc836'),
    category: 'Makanan',
    stock: 24,
    featured: false,
    sales_count: 44,
    rating: 4.9,
    reviews_count: 9,
    created_at: '2026-04-20T08:00:00.000Z',
  },
];

export const STATIC_REVIEWS = [
  {
    id: 'review-1',
    order_id: 'order-1',
    product_id: 'product-1',
    buyer_id: 'buyer-1',
    rating: 5,
    comment: 'Renyah dan manisnya pas. Pengiriman rapi.',
    created_at: '2026-05-16T08:00:00.000Z',
    orders: { buyer_name: 'Maya Lestari' },
  },
  {
    id: 'review-2',
    order_id: 'order-2',
    product_id: 'product-2',
    buyer_id: 'buyer-2',
    rating: 5,
    comment: 'Beseknya kokoh dan cocok untuk hantaran.',
    created_at: '2026-05-20T08:00:00.000Z',
    orders: { buyer_name: 'Rina Putri' },
  },
];

export const STATIC_ORDERS = [
  {
    id: 'DM-ORD-0001',
    buyer_id: 'demo-admin',
    store_id: 'store-1',
    total_amount: 51000,
    status: 'dikirim',
    payment_method: 'cod',
    shipping_address: 'Jl. Melati No. 8, Labuhan Maringgai',
    awb_number: 'JNE123456789',
    is_reviewed: false,
    created_at: '2026-05-28T08:00:00.000Z',
    updated_at: '2026-05-28T08:00:00.000Z',
    order_items: [
      {
        id: 'order-item-1',
        order_id: 'DM-ORD-0001',
        product_id: 'product-1',
        quantity: 2,
        price: 18000,
        products: STATIC_PRODUCTS[0],
      },
    ],
  },
  {
    id: 'DM-ORD-0002',
    buyer_id: 'demo-admin',
    store_id: 'store-2',
    total_amount: 39000,
    status: 'selesai',
    payment_method: 'cod',
    shipping_address: 'Dusun Sukamaju, Lampung Timur',
    is_reviewed: true,
    created_at: '2026-05-19T08:00:00.000Z',
    updated_at: '2026-05-20T08:00:00.000Z',
    order_items: [
      {
        id: 'order-item-2',
        order_id: 'DM-ORD-0002',
        product_id: 'product-2',
        quantity: 2,
        price: 12000,
        products: STATIC_PRODUCTS[1],
      },
    ],
  },
];

export const STATIC_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Operator Mesin Produksi',
    company: 'CV Maju Bersama',
    description: 'Dibutuhkan operator mesin produksi keripik, jujur dan teliti.',
    category: 'Produksi',
    type: 'full_time',
    location: 'Desa Labuhan Maringgai',
    deadline: '2026-06-23',
    salary_range: 'Rp 2.000.000 - Rp 2.500.000',
    requirements: ['Minimal SMA/SMK', 'Bersedia kerja shift', 'Pengalaman tidak diutamakan'],
    phone_number: '6281122334455',
    is_active: true,
    created_at: '2026-05-30T08:00:00.000Z',
  },
  {
    id: 'job-2',
    title: 'Admin Toko Online',
    company: 'Keripik Bu Sari',
    description: 'Mengelola pesanan online dan media sosial toko.',
    category: 'Administrasi',
    type: 'part_time',
    location: 'Remote / Desa',
    deadline: '2026-06-18',
    salary_range: 'Rp 1.000.000 - Rp 1.500.000',
    requirements: ['Menguasai media sosial', 'Bisa mengetik cepat'],
    phone_number: '6281234567890',
    is_active: true,
    created_at: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'job-3',
    title: 'Relawan Pengajar PAUD',
    company: 'PAUD Tunas Bangsa',
    description: 'Relawan mengajar anak usia dini, ramah dan sabar.',
    category: 'Pendidikan',
    type: 'volunteer',
    location: 'PAUD Tunas Bangsa',
    deadline: '2026-07-03',
    salary_range: 'Sukarela',
    requirements: ['Sabar dan ramah anak', 'Berkomitmen'],
    phone_number: '6285566778899',
    is_active: true,
    created_at: '2026-05-28T08:00:00.000Z',
  },
];

export const STATIC_ARTICLES: Article[] = [
  {
    id: 'article-1',
    title: 'Tips Memulai UMKM dari Rumah',
    excerpt: 'Panduan praktis memulai usaha kecil dengan modal terbatas.',
    content: 'Memulai UMKM dari rumah kini semakin mudah. Mulailah dari produk yang Anda kuasai, manfaatkan bahan lokal, dan pasarkan lewat marketplace desa serta media sosial.',
    category: 'UMKM',
    author: 'Admin DesaMind',
    image_url: img('1556761175-5973dc0f32e7'),
    is_published: true,
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'article-2',
    title: 'Pentingnya Gotong Royong di Era Modern',
    excerpt: 'Semangat gotong royong tetap relevan untuk membangun desa.',
    content: 'Gotong royong adalah warisan budaya yang memperkuat ikatan sosial. Di era modern, semangat ini bisa diwujudkan melalui kerja bakti, arisan, hingga kolaborasi digital.',
    category: 'Budaya',
    author: 'Kepala Desa',
    image_url: img('1517048676732-d65bc937f952'),
    is_published: true,
    created_at: '2026-05-24T08:00:00.000Z',
  },
  {
    id: 'article-3',
    title: 'Cara Menjaga Kebersihan Lingkungan Desa',
    excerpt: 'Langkah sederhana menjaga desa tetap bersih dan sehat.',
    content: 'Kebersihan lingkungan dimulai dari rumah masing-masing. Pisahkan sampah organik dan anorganik, kelola sampah dengan bijak, dan ikut serta dalam kerja bakti rutin.',
    category: 'Lingkungan',
    author: 'Admin DesaMind',
    image_url: img('1532996122724-e3c354a0b15b'),
    is_published: true,
    created_at: '2026-05-19T08:00:00.000Z',
  },
];

export const STATIC_TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'module-1',
    title: 'Dasar Pemasaran Digital untuk UMKM',
    description: 'Belajar memasarkan produk lewat media sosial dan marketplace.',
    category: 'Bisnis & Marketing',
    level: 'Pemula',
    duration_minutes: 90,
    image_url: img('1460925895917-afdab827c52f'),
    instructor: 'Tim DesaMind',
    lessons: [
      { title: 'Mengenal Marketing Digital', duration: 20 },
      { title: 'Membuat Konten Menarik', duration: 35 },
      { title: 'Strategi Marketplace', duration: 35 },
    ],
    rating: 4.8,
    enrolled: 45,
    is_published: true,
    created_at: '2026-05-14T08:00:00.000Z',
  },
  {
    id: 'module-2',
    title: 'Manajemen Keuangan Usaha Kecil',
    description: 'Mengelola arus kas dan pembukuan sederhana usaha.',
    category: 'Keuangan',
    level: 'Pemula',
    duration_minutes: 75,
    image_url: img('1554224155-6726b3ff858f'),
    instructor: 'Tim DesaMind',
    lessons: [
      { title: 'Pencatatan Keuangan', duration: 30 },
      { title: 'Menghitung Laba', duration: 45 },
    ],
    rating: 4.6,
    enrolled: 30,
    is_published: true,
    created_at: '2026-05-16T08:00:00.000Z',
  },
  {
    id: 'module-3',
    title: 'Bertani Organik Modern',
    description: 'Teknik pertanian organik yang ramah lingkungan dan menguntungkan.',
    category: 'Pertanian',
    level: 'Menengah',
    duration_minutes: 120,
    image_url: img('1625246333195-78d9c38ad449'),
    instructor: 'Penyuluh Pertanian',
    lessons: [
      { title: 'Pengenalan Organik', duration: 40 },
      { title: 'Pembuatan Pupuk Kompos', duration: 40 },
      { title: 'Pengendalian Hama Alami', duration: 40 },
    ],
    rating: 4.9,
    enrolled: 25,
    is_published: true,
    created_at: '2026-05-22T08:00:00.000Z',
  },
];

export const STATIC_ACTIONS: CommunityAction[] = [
  {
    id: 'action-1',
    title: 'Kerja Bakti Bersih Sungai',
    description: 'Membersihkan sungai desa dari sampah dan eceng gondok bersama warga.',
    category: 'Lingkungan',
    location: 'Sungai Way Sekampung',
    date: '2026-06-10',
    time: '07:00',
    max_participants: 50,
    current_participants: 23,
    organizer: 'Karang Taruna',
    image_url: img('1532996122724-e3c354a0b15b'),
    status: 'open',
    created_at: '2026-05-31T08:00:00.000Z',
  },
  {
    id: 'action-2',
    title: 'Penanaman 1000 Pohon',
    description: 'Gerakan penghijauan menanam pohon di area lahan kritis desa.',
    category: 'Lingkungan',
    location: 'Bukit Desa',
    date: '2026-06-17',
    time: '08:00',
    max_participants: 100,
    current_participants: 67,
    organizer: 'Pemerintah Desa',
    image_url: img('1466692476868-aef1dfb1e735'),
    status: 'open',
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'action-3',
    title: 'Posyandu Balita Bulanan',
    description: 'Kegiatan rutin penimbangan dan imunisasi balita.',
    category: 'Kesehatan',
    location: 'Balai Desa',
    date: '2026-06-06',
    time: '09:00',
    max_participants: 40,
    current_participants: 40,
    organizer: 'Kader Posyandu',
    image_url: img('1576091160399-112ba8d25d1d'),
    status: 'full',
    created_at: '2026-05-26T08:00:00.000Z',
  },
];

export const STATIC_ACTION_PARTICIPANTS = [
  { id: 'participant-1', action_id: 'action-1', user_id: 'user-1', name: 'Nina Rahma', email: 'nina@example.com', created_at: '2026-06-01T08:00:00.000Z' },
  { id: 'participant-2', action_id: 'action-1', user_id: 'user-2', name: 'Agus Salim', email: 'agus@example.com', created_at: '2026-06-01T09:00:00.000Z' },
  { id: 'participant-3', action_id: 'action-2', user_id: 'user-3', name: 'Laila Fitri', email: 'laila@example.com', created_at: '2026-06-02T10:00:00.000Z' },
];

export const STATIC_ANNOUNCEMENTS: Announcement[] = [
  { id: 'ann-1', title: 'Jadwal Pelayanan Administrasi Desa', category: 'Pemerintahan', content: 'Pelayanan administrasi desa buka Senin-Kamis 08:00-15:00 WIB dan Jumat 08:00-11:30 WIB.', date: '2026-06-01T08:00:00.000Z', is_important: true },
  { id: 'ann-2', title: 'Pembagian BLT Dana Desa Tahap II', category: 'Sosial', content: 'Pembagian BLT Dana Desa tahap II akan dilaksanakan pada tanggal 10 bulan ini di Balai Desa. Mohon membawa KTP dan KK asli.', date: '2026-05-30T08:00:00.000Z', is_important: true },
  { id: 'ann-3', title: 'Vaksinasi Hewan Ternak Gratis', category: 'Kesehatan', content: 'Dinas Peternakan mengadakan vaksinasi gratis untuk hewan ternak warga. Daftar di kantor desa.', date: '2026-05-28T08:00:00.000Z', is_important: false },
];

export const STATIC_GALLERY: GalleryItem[] = [
  { id: 'gallery-1', title: 'Kerja Bakti Mingguan', category: 'Kerja Bakti', date: '2026-05-27', image_url: img('1517048676732-d65bc937f952') },
  { id: 'gallery-2', title: 'Kegiatan PKK', category: 'PKK', date: '2026-05-20', image_url: img('1488521787991-ed7bbaae773c') },
  { id: 'gallery-3', title: 'Posyandu Balita', category: 'Posyandu', date: '2026-05-13', image_url: img('1576091160399-112ba8d25d1d') },
  { id: 'gallery-4', title: 'Latihan Karang Taruna', category: 'Karang Taruna', date: '2026-05-06', image_url: img('1529156069898-49953e39b3ac') },
];

export const STATIC_PROJECTS: Project[] = [
  {
    id: 'project-1',
    title: 'Pembangunan Jalan Desa',
    description: 'Pengaspalan jalan utama desa sepanjang 2 km.',
    budget: 350000000,
    spent: 210000000,
    progress: 60,
    status: 'ongoing',
    category: 'Infrastruktur',
    image_url: img('1503387762-592deb58ef4e'),
    start_date: '2026-04-04',
    end_date: '2026-07-03',
    contractor: 'CV Karya Bangun',
    created_at: '2026-04-04T08:00:00.000Z',
  },
  {
    id: 'project-2',
    title: 'Renovasi Balai Desa',
    description: 'Perbaikan dan perluasan gedung balai desa.',
    budget: 150000000,
    spent: 150000000,
    progress: 100,
    status: 'completed',
    category: 'Infrastruktur',
    image_url: img('1486406146926-c627a92ad1ab'),
    start_date: '2026-02-03',
    end_date: '2026-05-14',
    contractor: 'CV Maju Jaya',
    created_at: '2026-02-03T08:00:00.000Z',
  },
  {
    id: 'project-3',
    title: 'Pengadaan Air Bersih',
    description: 'Instalasi sumur bor dan pipa distribusi air bersih.',
    budget: 200000000,
    spent: 50000000,
    progress: 25,
    status: 'ongoing',
    category: 'Kesehatan',
    image_url: img('1538300342682-cf57afb97285'),
    start_date: '2026-05-04',
    end_date: '2026-08-02',
    contractor: 'PT Tirta Sehat',
    created_at: '2026-05-04T08:00:00.000Z',
  },
];

export const STATIC_APB_DESA: APBDesa = {
  year: 2026,
  total_budget: 1500000000,
  realized: 920000000,
  allocations: [
    { category: 'Pembangunan', amount: 600000000, color: '#2E6B5E' },
    { category: 'Pemberdayaan', amount: 350000000, color: '#E8B04B' },
    { category: 'Pemerintahan', amount: 300000000, color: '#3B82F6' },
    { category: 'Pembinaan', amount: 150000000, color: '#A855F7' },
    { category: 'Tak Terduga', amount: 100000000, color: '#EF4444' },
  ],
  programs: [
    { name: 'Pembangunan Jalan Desa', category: 'Pembangunan', budget: 350000000, status: 'Berjalan' },
    { name: 'Renovasi Balai Desa', category: 'Pembangunan', budget: 150000000, status: 'Selesai' },
    { name: 'Pelatihan UMKM', category: 'Pemberdayaan', budget: 100000000, status: 'Berjalan' },
    { name: 'Posyandu & Kesehatan', category: 'Pembinaan', budget: 80000000, status: 'Berjalan' },
    { name: 'Pengadaan Air Bersih', category: 'Pembangunan', budget: 200000000, status: 'Berjalan' },
  ],
};

export const STATIC_USERS: AuthUser[] = [
  {
    id: 'demo-admin',
    email: 'admin@desamind.id',
    name: 'Admin DesaMind',
    role: 'admin',
    status: 'active',
    avatar: 'AD',
    created_at: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'demo-warga',
    email: 'warga@desamind.id',
    name: 'Warga Demo',
    role: 'warga',
    status: 'active',
    avatar: 'WD',
    created_at: '2026-02-01T08:00:00.000Z',
  },
];

export const STATIC_HEALTH_SCORE: HealthScore = {
  overall: 78,
  grade: 'Baik',
  metrics: {
    cleanliness: 72,
    infrastructure: 70,
    safety: 80,
    health: 82,
    economy: 76,
    community: 88,
  },
  trend: 'naik',
  ai_narrative: 'Kondisi desa berada pada kategori baik. Prioritas terdekat adalah percepatan penyelesaian laporan infrastruktur dan menjaga ritme kegiatan warga.',
  last_updated: '2026-06-03T08:00:00.000Z',
  source_stats: {
    reports: { total: 5, pending: 2, in_progress: 2, completed: 1 },
    projects: { total: 3, average_progress: 62 },
    community: { actions: 3, participants: 130 },
    economy: { active_stores: 3, paid_orders: 2, active_jobs: 3 },
    emergency: { active: 0, resolved: 4 },
  },
};

export const STATIC_PREDICTIONS: AIPrediction[] = [
  {
    id: 'pred-1',
    category: 'Infrastruktur',
    risk_level: 'Sedang',
    confidence: 78,
    title: 'Perbaikan Jalan Perlu Diprioritaskan',
    description: 'Beberapa laporan infrastruktur masih aktif dan berpotensi mengganggu mobilitas warga.',
    recommendation: 'Jadwalkan survei teknis dan alokasikan perbaikan sementara pada titik jalan yang paling sering dilalui.',
    icon: '!',
  },
  {
    id: 'pred-2',
    category: 'Lingkungan',
    risk_level: 'Rendah',
    confidence: 68,
    title: 'Kebersihan Lingkungan Stabil',
    description: 'Kegiatan warga dan pengangkutan sampah tambahan membantu menjaga kondisi lingkungan.',
    recommendation: 'Pertahankan jadwal kerja bakti dan tambahkan edukasi pemilahan sampah rumah tangga.',
    icon: '*',
  },
  {
    id: 'pred-3',
    category: 'Ekonomi',
    risk_level: 'Rendah',
    confidence: 72,
    title: 'UMKM Lokal Menunjukkan Aktivitas Baik',
    description: 'Produk unggulan dan toko aktif memberi sinyal ekonomi lokal yang sehat.',
    recommendation: 'Dorong pelatihan pemasaran digital dan foto produk untuk memperluas jangkauan pembeli.',
    icon: '$',
  },
];

export const STATIC_DASHBOARD_STATS: DashboardStats = {
  totalReports: STATIC_REPORTS.length,
  pendingReports: STATIC_REPORTS.filter((report) => report.status === 'pending').length,
  inProgressReports: STATIC_REPORTS.filter((report) => report.status === 'in_progress').length,
  completedReports: STATIC_REPORTS.filter((report) => report.status === 'completed').length,
  resolutionRate: 20,
  activeUMKM: STATIC_STORES.length,
  totalCitizens: 1284,
  categoryData: [
    { category: 'Infrastruktur', count: 1 },
    { category: 'Sampah', count: 1 },
    { category: 'Keamanan', count: 1 },
    { category: 'Lingkungan', count: 1 },
    { category: 'Kesehatan', count: 1 },
  ],
  trendData: [
    { month: 'Jan', laporan: 5, selesai: 3 },
    { month: 'Feb', laporan: 8, selesai: 5 },
    { month: 'Mar', laporan: 10, selesai: 7 },
    { month: 'Apr', laporan: 7, selesai: 6 },
    { month: 'Mei', laporan: 12, selesai: 8 },
    { month: 'Jun', laporan: 5, selesai: 1 },
  ],
};

export const STATIC_UMKM_STATS = {
  activeStores: STATIC_STORES.length,
  verifiedStores: STATIC_STORES.length,
  soldProducts: STATIC_PRODUCTS.reduce((sum, product) => sum + Number(product.sales_count ?? 0), 0),
  averageRating: 4.8,
  reviewsCount: STATIC_PRODUCTS.reduce((sum, product) => sum + Number(product.reviews_count ?? 0), 0),
};

export const STATIC_TABLES: Record<string, unknown[]> = {
  reports: STATIC_REPORTS,
  products: STATIC_PRODUCTS,
  stores: STATIC_STORES,
  jobs: STATIC_JOBS,
  articles: STATIC_ARTICLES,
  training_modules: STATIC_TRAINING_MODULES,
  community_actions: STATIC_ACTIONS,
  announcements: STATIC_ANNOUNCEMENTS,
  gallery: STATIC_GALLERY,
  projects: STATIC_PROJECTS,
  users: STATIC_USERS,
};
