import type {
  APBDesa,
  AIPrediction,
  Announcement,
  Article,
  Comment,
  CommunityAction,
  DashboardStats,
  GalleryItem,
  HealthScore,
  Job,
  Product,
  Project,
  Report,
  ReportHistory,
  TrainingModule,
} from '@/lib/types';
import type { AppSettings } from '@/lib/map-settings';
import type { AuthUser } from '@/lib/auth';

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/photo-${id}?q=80&w=${w}&auto=format&fit=crop`;

const aiImg = (prompt: string, w = 800, h = 600) => {
  const keywords = encodeURIComponent(prompt.replace(/ /g, ','));
  return `https://loremflickr.com/${w}/${h}/${keywords}`;
};

export const STATIC_APP_SETTINGS: AppSettings = {
  village_name: 'Labuhan Maringgai',
  district_name: 'Labuhan Maringgai',
  city_name: 'Lampung Timur',
  province_name: 'Lampung',
  center_lat: -5.3428912,
  center_lng: 105.7938069,
  boundary_geojson: [
    [
      [105.750, -5.310],
      [105.805, -5.320],
      [105.820, -5.350],
      [105.800, -5.365],
      [105.760, -5.355],
      [105.750, -5.310],
    ],
  ],
  fallback_radius_m: 2500,
};

export const STATIC_REPORTS: Report[] = [
  {
    id: 'report-1',
    user_id: 'user-warga',
    author_name: 'Budi Santoso',
    title: 'Jalan berlubang di RT 02',
    title_en: 'Pothole in RT 02',
    description: 'Lubang besar di Jalan Melati dekat balai desa sangat membahayakan pengendara motor terutama saat malam hari.',
    description_en: 'A large pothole on Melati Street near the village hall is very dangerous for motorcyclists, especially at night.',
    category: 'Infrastruktur',
    category_en: 'Infrastructure',
    status: 'in_progress',
    lat: -5.3429,
    lng: 105.7938,
    image_url: 'https://asset-2.tribunnews.com/manado/foto/bank/images/jalan-berlubang-di-Kelurahan-Gogagoman-Kotamobagu-Senin-1-Juni-2026-as.jpg',
    upvotes: 12,
    comments_count: 2,
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'report-2',
    user_id: 'user-warga',
    author_name: 'Siti Aminah',
    title: 'Tumpukan sampah di pasar',
    title_en: 'Piled up trash at the market',
    description: 'Sampah menumpuk di belakang pasar desa sudah 3 hari belum diangkut, menimbulkan bau tidak sedap.',
    description_en: 'Trash has been piling up behind the village market for 3 days and hasn\'t been collected, causing a foul odor.',
    category: 'Sampah',
    category_en: 'Waste',
    status: 'pending',
    lat: -5.344,
    lng: 105.795,
    image_url: 'https://cdn.antarafoto.com/cache/1200x800/2016/02/02/penumpukan-sampah-di-pasar-cbh5-dom.jpg',
    upvotes: 8,
    comments_count: 1,
    created_at: '2026-05-31T08:00:00.000Z',
  },
  {
    id: 'report-3',
    user_id: 'user-warga',
    author_name: 'Andi Pratama',
    title: 'Lampu jalan mati di gang utama',
    title_en: 'Street light is out in the main alley',
    description: 'Lampu penerangan jalan umum di gang utama RW 03 mati total, rawan tindak kejahatan.',
    description_en: 'The public street light in the main alley of RW 03 is completely out, prone to crime.',
    category: 'Keamanan',
    category_en: 'Security',
    status: 'completed',
    lat: -5.341,
    lng: 105.792,
    image_url: 'https://tse4.mm.bing.net/th/id/OIP.BfDUYkjeQvO_jRLvgWV31gHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
    upvotes: 20,
    comments_count: 1,
    created_at: '2026-05-20T08:00:00.000Z',
  },
  {
    id: 'report-4',
    user_id: 'user-warga',
    author_name: 'Dewi Lestari',
    title: 'Saluran irigasi tersumbat',
    title_en: 'Clogged irrigation canal',
    description: 'Saluran irigasi sawah tersumbat sampah dan lumpur, air tidak mengalir ke area persawahan warga.',
    description_en: 'The rice field irrigation canal is clogged with trash and mud, water is not flowing to the farming area.',
    category: 'Lingkungan',
    category_en: 'Environment',
    status: 'pending',
    lat: -5.345,
    lng: 105.796,
    image_url: 'https://tse1.mm.bing.net/th/id/OIP.8BpGDIi9Tu5nNL8SqQ5xdgHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
    upvotes: 5,
    comments_count: 0,
    created_at: '2026-06-02T08:00:00.000Z',
  },
  {
    id: 'report-5',
    user_id: 'user-warga',
    author_name: 'Rahmat Hidayat',
    title: 'Posyandu butuh perlengkapan',
    title_en: 'Posyandu needs equipment',
    description: 'Posyandu Melati kekurangan timbangan bayi dan alat ukur tinggi badan untuk kegiatan rutin bulanan.',
    description_en: 'Posyandu Melati lacks a baby scale and height measuring tool for routine monthly activities.',
    category: 'Kesehatan',
    category_en: 'Health',
    status: 'in_progress',
    lat: -5.3435,
    lng: 105.7945,
    image_url: 'https://tse3.mm.bing.net/th/id/OIP.wYqiydqOLLbsfQfGB9ToNAHaE-?rs=1&pid=ImgDetMain&o=7&rm=3',
    upvotes: 15,
    comments_count: 1,
    created_at: '2026-05-27T08:00:00.000Z',
  },
  {
    id: 'report-6',
    user_id: 'user-warga2',
    author_name: 'Hasan Basri',
    title: 'Banjir di RT 05 akibat luapan sungai',
    title_en: 'Flood in RT 05 due to overflowing river',
    description: 'Hujan deras semalaman membuat sungai meluap dan membanjiri jalanan serta beberapa rumah warga di RT 05.',
    description_en: 'Heavy rain all night caused the river to overflow and flood the streets and several houses in RT 05.',
    category: 'Lingkungan',
    category_en: 'Environment',
    status: 'pending',
    lat: -5.345,
    lng: 105.798,
    image_url: 'https://cdn1-production-images-kly.akamaized.net/oORQk77ED44bse6lgSIKw4Jxf6M=/1231x710/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4186417/original/031726500_1665384941-20221010-BANJIR-JAKARTA-FAIZAL-6.jpg',
    upvotes: 35,
    comments_count: 5,
    created_at: '2026-06-03T07:30:00.000Z',
  },
  {
    id: 'report-7',
    user_id: 'user-warga3',
    author_name: 'Bapak Supri',
    title: 'Pohon tumbang menghalangi jalan utama',
    title_en: 'Fallen tree blocking main road',
    description: 'Pohon beringin besar tumbang karena angin kencang, menghalangi akses jalan poros desa sepenuhnya.',
    description_en: 'A large banyan tree fell due to strong winds, completely blocking access to the village main road.',
    category: 'Infrastruktur',
    category_en: 'Infrastructure',
    status: 'in_progress',
    lat: -5.340,
    lng: 105.790,
    image_url: 'https://cdn.antaranews.com/cache/1200x800/2016/01/20160128015.jpg',
    upvotes: 42,
    comments_count: 8,
    created_at: '2026-06-02T15:20:00.000Z',
  },
  {
    id: 'report-8',
    user_id: 'user-warga4',
    author_name: 'Siti Maimunah',
    title: 'Pipa air bersih bocor',
    title_en: 'Clean water pipe leaking',
    description: 'Pipa saluran air bersih desa bocor parah di depan masjid, air terbuang sia-sia dan menggenangi halaman.',
    description_en: 'The village clean water pipe is leaking badly in front of the mosque, water is wasted and flooding the yard.',
    category: 'Infrastruktur',
    category_en: 'Infrastructure',
    status: 'pending',
    lat: -5.342,
    lng: 105.794,
    image_url: 'https://awsimages.detik.net.id/api/wm/2025/05/28/pipa-pdam-bocor-di-probolinggo-1748418723795_169.jpeg?wid=54&w=1200&v=1&t=jpeg',
    upvotes: 18,
    comments_count: 2,
    created_at: '2026-06-03T09:15:00.000Z',
  },
  {
    id: 'report-9',
    user_id: 'user-warga5',
    author_name: 'Agus Setiawan',
    title: 'Fasilitas taman bermain anak rusak',
    title_en: 'Children playground facilities damaged',
    description: 'Ayunan dan perosotan di taman desa rusak dan berkarat, sangat berbahaya bagi anak-anak yang bermain.',
    description_en: 'The swings and slides in the village park are damaged and rusty, very dangerous for playing children.',
    category: 'Fasilitas Umum',
    category_en: 'Public Facilities',
    status: 'pending',
    lat: -5.346,
    lng: 105.791,
    image_url: 'https://imgsrv2.voi.id/hQCIrlmRgWvpBIKTzGJjSdbtxTC8DkK25zgCfh7G5gM/auto/1200/675/sm/1/bG9jYWw6Ly8vcHVibGlzaGVycy84ODUwOS8yMDIxMDkyNTE1MjItbWFpbi5jcm9wcGVkXzE2MzI1NTgxNjkuanBn.jpg',
    upvotes: 25,
    comments_count: 4,
    created_at: '2026-06-01T16:45:00.000Z',
  },
  {
    id: 'report-10',
    user_id: 'user-warga6',
    author_name: 'Kusuma Wardhani',
    title: 'Kekeringan lahan pertanian',
    title_en: 'Agricultural land drought',
    description: 'Musim kemarau panjang membuat saluran irigasi kering, sawah warga terancam gagal panen.',
    description_en: 'The long dry season has dried up the irrigation canals, citizens\' rice fields are threatened with crop failure.',
    category: 'Pertanian',
    category_en: 'Agriculture',
    status: 'pending',
    lat: -5.350,
    lng: 105.799,
    image_url: 'https://static.republika.co.id/uploads/images/xlarge/052107200-1599397199-1280-856.jpg',
    upvotes: 55,
    comments_count: 12,
    created_at: '2026-05-28T10:00:00.000Z',
  },
];

export const STATIC_REPORT_COMMENTS: Comment[] = [
  { id: 'comment-1', report_id: 'report-1', author_name: 'Admin Desa', content: 'Tim sudah menjadwalkan survei lokasi.', created_at: '2026-05-30T09:00:00.000Z' },
  { id: 'comment-2', report_id: 'report-1', author_name: 'Warga', content: 'Mohon dipasang tanda sementara karena cukup berbahaya.', created_at: '2026-05-30T13:00:00.000Z' },
  { id: 'comment-3', report_id: 'report-2', author_name: 'Petugas Kebersihan', content: 'Pengangkutan tambahan dijadwalkan sore ini.', created_at: '2026-06-01T08:30:00.000Z' },
  { id: 'comment-4', report_id: 'report-3', author_name: 'Admin Desa', content: 'Lampu sudah diperbaiki dan menyala normal.', created_at: '2026-05-22T10:00:00.000Z' },
  { id: 'comment-5', report_id: 'report-5', author_name: 'Kader Posyandu', content: 'Daftar kebutuhan sudah kami teruskan ke perangkat desa.', created_at: '2026-05-28T11:00:00.000Z' },
];

export const STATIC_REPORT_HISTORY: ReportHistory[] = [
  { id: 'hist-1', report_id: 'report-1', status: 'pending', note: 'Laporan masuk dan menunggu verifikasi.', changed_by: 'Sistem', created_at: '2026-05-29T08:00:00.000Z' },
  { id: 'hist-2', report_id: 'report-1', status: 'in_progress', note: 'Tim teknis dijadwalkan melakukan survei.', changed_by: 'Admin Desa', created_at: '2026-05-30T08:00:00.000Z' },
  { id: 'hist-3', report_id: 'report-3', status: 'pending', note: 'Laporan diterima.', changed_by: 'Sistem', created_at: '2026-05-20T08:00:00.000Z' },
  { id: 'hist-4', report_id: 'report-3', status: 'completed', note: 'Lampu jalan selesai diperbaiki.', changed_by: 'Admin Desa', created_at: '2026-05-22T10:00:00.000Z' },
];

export const STATIC_STORES = [
  {
    id: 'store-1',
    user_id: 'demo-admin',
    name: 'Warung Bu Sari',
    description: 'Produk makanan ringan rumahan dari bahan lokal desa.',
    address: 'Jl. Melati No. 12, Labuhan Maringgai',
    logo_url: img('1542838132-92c53300491e', 300),
    status: 'active',
    created_at: '2026-01-14T08:00:00.000Z',
  },
  {
    id: 'store-2',
    user_id: 'seller-2',
    name: 'Kriya Bambu Maringgai',
    description: 'Kerajinan bambu dan anyaman untuk kebutuhan rumah tangga.',
    address: 'Dusun Sukamaju, Lampung Timur',
    logo_url: img('1513519245088-0e12902e35ca', 300),
    status: 'active',
    created_at: '2026-02-02T08:00:00.000Z',
  },
  {
    id: 'store-3',
    user_id: 'seller-3',
    name: 'Tani Segar Desa',
    description: 'Hasil panen segar langsung dari petani lokal.',
    address: 'Area Pasar Desa Labuhan Maringgai',
    logo_url: img('1500937386664-56d1dfef3854', 300),
    status: 'active',
    created_at: '2026-03-05T08:00:00.000Z',
  },
  {
    id: 'store-4',
    user_id: 'seller-4',
    name: 'Bengkel Motor Berkah',
    description: 'Melayani servis motor, ganti oli, dan tambal ban.',
    address: 'Jl. Poros Utama No. 45, Labuhan Maringgai',
    logo_url: aiImg('motorcycle repair shop rural garage local mechanic logo'),
    status: 'active',
    created_at: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'store-5',
    user_id: 'seller-5',
    name: 'Toko Pertanian Subur',
    description: 'Menyediakan pupuk, bibit unggul, dan obat-obatan pertanian.',
    address: 'Kawasan Pasar Inpres Desa',
    logo_url: aiImg('agricultural supply store fertilizer seeds shop local rural'),
    status: 'active',
    created_at: '2026-04-15T08:00:00.000Z',
  },
  {
    id: 'store-6',
    user_id: 'seller-6',
    name: 'Warung Kopi Ndeso',
    description: 'Tempat nongkrong asik warga desa, kopi robusta lokal, dan gorengan hangat.',
    address: 'Simpang Tiga Desa',
    logo_url: aiImg('rustic village coffee shop warm lighting local warung kopi'),
    status: 'active',
    created_at: '2026-05-01T08:00:00.000Z',
  },
];

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'product-1',
    user_id: 'demo-admin',
    store_id: 'store-1',
    seller_name: 'Warung Bu Sari',
    name: 'Keripik Pisang Manis',
    name_en: 'Sweet Banana Chips',
    description: 'Keripik pisang renyah dengan rasa manis gurih, cocok untuk camilan keluarga.',
    description_en: 'Crunchy banana chips with a sweet and savory taste, perfect for family snacks.',
    price: 18000,
    phone_number: '6281234567890',
    whatsapp: '6281234567890',
    image_url: 'https://cdn11.bigcommerce.com/s-5wf0xbtgyb/images/stencil/1280x1280/products/4807/13441/Resep-Keripik-Pisang__15964.1692765380.jpg?c=2',
    category: 'Makanan',
    category_en: 'Food',
    stock: 48,
    featured: true,
    sales_count: 124,
    rating: 4.8,
    reviews_count: 18,
    created_at: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'product-2',
    user_id: 'seller-2',
    store_id: 'store-2',
    seller_name: 'Kriya Bambu Maringgai',
    name: 'Besek Bambu Handmade',
    name_en: 'Handmade Bamboo Basket',
    description: 'Besek bambu kuat dan rapi untuk hantaran, kemasan makanan, atau dekorasi.',
    description_en: 'Strong and neat bamboo basket for gifts, food packaging, or decoration.',
    price: 12000,
    phone_number: '6281122334455',
    whatsapp: '6281122334455',
    image_url: 'https://down-id.img.susercontent.com/file/sg-11134201-7rdw1-mboolmppvswq7b',
    category: 'Kerajinan',
    category_en: 'Crafts',
    stock: 80,
    featured: true,
    sales_count: 76,
    rating: 4.7,
    reviews_count: 11,
    created_at: '2026-04-12T08:00:00.000Z',
  },
  {
    id: 'product-3',
    user_id: 'seller-3',
    store_id: 'store-3',
    seller_name: 'Tani Segar Desa',
    name: 'Sayur Organik Pakcoy',
    name_en: 'Organic Pakcoy Vegetables',
    description: 'Pakcoy segar tanpa pestisida berat, dipanen pagi hari.',
    description_en: 'Fresh pakcoy without heavy pesticides, harvested in the morning.',
    price: 9000,
    phone_number: '6285566778899',
    whatsapp: '6285566778899',
    image_url: 'https://cf.shopee.co.id/file/a705d81b5c17a35752efad139d914b42',
    category: 'Pertanian',
    category_en: 'Agriculture',
    stock: 35,
    featured: false,
    sales_count: 58,
    rating: 4.6,
    reviews_count: 7,
    created_at: '2026-04-18T08:00:00.000Z',
  },
  {
    id: 'product-4',
    user_id: 'demo-admin',
    store_id: 'store-1',
    seller_name: 'Warung Bu Sari',
    name: 'Sambal Terasi Rumahan',
    name_en: 'Homemade Shrimp Paste Sambal',
    description: 'Sambal terasi pedas harum dalam kemasan botol higienis.',
    description_en: 'Fragrant spicy shrimp paste sambal in hygienic bottle packaging.',
    price: 22000,
    phone_number: '6281234567890',
    whatsapp: '6281234567890',
    image_url: 'https://th.bing.com/th/id/R.c972f2065481d474873833ce1ad81878?rik=rvtjey35KOZzYA&riu=http%3a%2f%2fby-ncc.com%2fcdn%2fshop%2fproducts%2fsambal-terasi-pedas-gurih-ala-rumahan-bumbu-masak-cepat-saji-termurah-byncc-215480.jpg%3fv%3d1708682793&ehk=sKrxjFvQThWPr0B%2bL%2fmKH4CpTJHq05nOdUhaq4qIVrM%3d&risl=&pid=ImgRaw&r=0',
    category: 'Makanan',
    category_en: 'Food',
    stock: 24,
    featured: false,
    sales_count: 44,
    rating: 4.9,
    reviews_count: 9,
    created_at: '2026-04-20T08:00:00.000Z',
  },
  {
    id: 'product-5',
    user_id: 'seller-4',
    store_id: 'store-4',
    seller_name: 'Bengkel Motor Berkah',
    name: 'Jasa Servis Ringan Motor Matic',
    name_en: 'Matic Motorcycle Light Service',
    description: 'Servis rutin bersihkan karburator/injeksi, cek rem, dan tune up.',
    description_en: 'Routine service to clean carburetor/injection, check brakes, and tune up.',
    price: 45000,
    phone_number: '628111222333',
    whatsapp: '628111222333',
    image_url: 'https://tse3.mm.bing.net/th/id/OIP.1vVRop2gKPM9qjDR57FGAgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Jasa',
    category_en: 'Service',
    stock: 999,
    featured: true,
    sales_count: 150,
    rating: 4.8,
    reviews_count: 22,
    created_at: '2026-05-01T08:00:00.000Z',
  },
  {
    id: 'product-6',
    user_id: 'seller-5',
    store_id: 'store-5',
    seller_name: 'Toko Pertanian Subur',
    name: 'Pupuk Kompos Organik 5Kg',
    name_en: 'Organic Compost Fertilizer 5Kg',
    description: 'Pupuk kompos ramah lingkungan buatan kelompok tani lokal.',
    description_en: 'Eco-friendly compost fertilizer made by local farming groups.',
    price: 25000,
    phone_number: '628222333444',
    whatsapp: '628222333444',
    image_url: 'https://tse2.mm.bing.net/th/id/OIP.k99QN1QT79ICXkV7V2xccgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Pertanian',
    category_en: 'Agriculture',
    stock: 120,
    featured: false,
    sales_count: 85,
    rating: 4.9,
    reviews_count: 15,
    created_at: '2026-05-05T08:00:00.000Z',
  },
  {
    id: 'product-7',
    user_id: 'seller-6',
    store_id: 'store-6',
    seller_name: 'Warung Kopi Ndeso',
    name: 'Kopi Hitam Robusta Asli',
    description: 'Kopi hitam seduh dari biji robusta pilihan kebun desa.',
    price: 5000,
    phone_number: '628333444555',
    whatsapp: '628333444555',
    image_url: 'https://down-id.img.susercontent.com/file/id-11134207-7rasj-m0nqodoq92za52',
    category: 'Makanan',
    stock: 999,
    featured: true,
    sales_count: 500,
    rating: 4.9,
    reviews_count: 120,
    created_at: '2026-05-10T08:00:00.000Z',
  },
  {
    id: 'product-8',
    user_id: 'seller-2',
    store_id: 'store-2',
    seller_name: 'Kriya Bambu Maringgai',
    name: 'Tampah Bambu Tradisional',
    description: 'Tampah bambu anyaman tangan, ukuran diameter 50cm.',
    price: 35000,
    phone_number: '6281122334455',
    whatsapp: '6281122334455',
    image_url: 'https://tse4.mm.bing.net/th/id/OIP.rorj_fgop2dUwyZzevNbdgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Kerajinan',
    stock: 45,
    featured: false,
    sales_count: 30,
    rating: 4.7,
    reviews_count: 8,
    created_at: '2026-05-15T08:00:00.000Z',
  },
];

export const STATIC_REVIEWS = [
  {
    id: 'review-1',
    order_id: 'order-1',
    product_id: 'product-1',
    buyer_id: 'buyer-1',
    rating: 5,
    comment: 'Renyah dan manisnya pas. Pengiriman rapi.',
    created_at: '2026-05-16T08:00:00.000Z',
    orders: { buyer_name: 'Maya Lestari' },
  },
  {
    id: 'review-2',
    order_id: 'order-2',
    product_id: 'product-2',
    buyer_id: 'buyer-2',
    rating: 5,
    comment: 'Beseknya kokoh dan cocok untuk hantaran.',
    created_at: '2026-05-20T08:00:00.000Z',
    orders: { buyer_name: 'Rina Putri' },
  },
];

export const STATIC_ORDERS = [
  {
    id: 'DM-ORD-0001',
    buyer_id: 'demo-admin',
    store_id: 'store-1',
    total_amount: 51000,
    status: 'dikirim',
    payment_method: 'cod',
    shipping_address: 'Jl. Melati No. 8, Labuhan Maringgai',
    awb_number: 'JNE123456789',
    is_reviewed: false,
    created_at: '2026-05-28T08:00:00.000Z',
    updated_at: '2026-05-28T08:00:00.000Z',
    order_items: [
      {
        id: 'order-item-1',
        order_id: 'DM-ORD-0001',
        product_id: 'product-1',
        quantity: 2,
        price: 18000,
        products: STATIC_PRODUCTS[0],
      },
    ],
  },
  {
    id: 'DM-ORD-0002',
    buyer_id: 'demo-admin',
    store_id: 'store-2',
    total_amount: 39000,
    status: 'selesai',
    payment_method: 'cod',
    shipping_address: 'Dusun Sukamaju, Lampung Timur',
    is_reviewed: true,
    created_at: '2026-05-19T08:00:00.000Z',
    updated_at: '2026-05-20T08:00:00.000Z',
    order_items: [
      {
        id: 'order-item-2',
        order_id: 'DM-ORD-0002',
        product_id: 'product-2',
        quantity: 2,
        price: 12000,
        products: STATIC_PRODUCTS[1],
      },
    ],
  },
];

export const STATIC_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Operator Mesin Produksi',
    company: 'CV Maju Bersama',
    description: 'Dibutuhkan operator mesin produksi keripik, jujur dan teliti.',
    category: 'Produksi',
    type: 'full_time',
    location: 'Desa Labuhan Maringgai',
    deadline: '2026-06-23',
    salary_range: 'Rp 2.000.000 - Rp 2.500.000',
    requirements: ['Minimal SMA/SMK', 'Bersedia kerja shift', 'Pengalaman tidak diutamakan'],
    phone_number: '6281122334455',
    is_active: true,
    created_at: '2026-05-30T08:00:00.000Z',
  },
  {
    id: 'job-2',
    title: 'Admin Toko Online',
    company: 'Keripik Bu Sari',
    description: 'Mengelola pesanan online dan media sosial toko.',
    category: 'Administrasi',
    type: 'part_time',
    location: 'Remote / Desa',
    deadline: '2026-06-18',
    salary_range: 'Rp 1.000.000 - Rp 1.500.000',
    requirements: ['Menguasai media sosial', 'Bisa mengetik cepat'],
    phone_number: '6281234567890',
    is_active: true,
    created_at: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'job-3',
    title: 'Relawan Pengajar PAUD',
    company: 'PAUD Tunas Bangsa',
    description: 'Relawan mengajar anak usia dini, ramah dan sabar.',
    category: 'Pendidikan',
    type: 'volunteer',
    location: 'PAUD Tunas Bangsa',
    deadline: '2026-07-03',
    salary_range: 'Sukarela',
    requirements: ['Sabar dan ramah anak', 'Berkomitmen'],
    phone_number: '6285566778899',
    is_active: true,
    created_at: '2026-05-28T08:00:00.000Z',
  },
  {
    id: 'job-4',
    title: 'Guru Honorer SD IT',
    company: 'SD IT Al-Hikmah',
    description: 'Dibutuhkan guru kelas untuk sekolah dasar, diutamakan S1 PGSD.',
    category: 'Pendidikan',
    type: 'full_time',
    location: 'Desa Labuhan Maringgai',
    deadline: '2026-07-15',
    salary_range: 'Rp 1.500.000 - Rp 2.000.000',
    requirements: ['S1 PGSD', 'Menyukai anak-anak', 'Berpengalaman mengajar lebih disukai'],
    phone_number: '6282233445566',
    is_active: true,
    created_at: '2026-06-02T08:00:00.000Z',
  },
  {
    id: 'job-5',
    title: 'Kurir Pengiriman Paket Desa',
    company: 'Desa Ekspedisi',
    description: 'Mencari kurir untuk pengiriman paket di area desa dan sekitarnya.',
    category: 'Logistik',
    type: 'full_time',
    location: 'Kantor Logistik Desa',
    deadline: '2026-06-30',
    salary_range: 'Rp 1.800.000 - Rp 2.500.000 + Insentif',
    requirements: ['Memiliki SIM C aktif', 'Punya motor pribadi', 'Hafal jalan desa'],
    phone_number: '6289988776655',
    is_active: true,
    created_at: '2026-06-03T08:00:00.000Z',
  },
];

export const STATIC_ARTICLES: Article[] = [
  {
    id: 'article-1',
    title: 'Tips Memulai UMKM dari Rumah',
    title_en: 'Tips for Starting a Business from Home',
    excerpt: 'Panduan praktis memulai usaha kecil dengan modal terbatas.',
    excerpt_en: 'A practical guide to starting a small business with limited capital.',
    content: 'Memulai UMKM dari rumah kini semakin mudah. Mulailah dari produk yang Anda kuasai, manfaatkan bahan lokal, dan pasarkan lewat marketplace desa serta media sosial.',
    category: 'UMKM',
    category_en: 'Business',
    author: 'Admin DesaMind',
    image_url: 'https://cdn.prod.website-files.com/60865b2e948bd69b89087ef2/61bc022441398494b45a4198_BLOG_-_5_Ide_Usaha_UMKM_Rumahan_yang_Menjanjikan_%5BMKT_Marketing_13-12-2021%5D-01.jpg',
    is_published: true,
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'article-2',
    title: 'Pentingnya Gotong Royong di Era Modern',
    title_en: 'The Importance of Mutual Cooperation in the Modern Era',
    excerpt: 'Semangat gotong royong tetap relevan untuk membangun desa.',
    excerpt_en: 'The spirit of mutual cooperation remains relevant for building the village.',
    content: 'Gotong royong adalah warisan budaya yang memperkuat ikatan sosial. Di era modern, semangat ini bisa diwujudkan melalui kerja bakti, arisan, hingga kolaborasi digital.',
    category: 'Budaya',
    category_en: 'Culture',
    author: 'Kepala Desa',
    image_url: 'https://nnc-media.netralnews.com/2025/04/IMG-Netral-News-User-13395-EF06LAUT9M.jpg',
    is_published: true,
    created_at: '2026-05-24T08:00:00.000Z',
  },
  {
    id: 'article-3',
    title: 'Cara Menjaga Kebersihan Lingkungan Desa',
    title_en: 'How to Maintain Village Environmental Cleanliness',
    excerpt: 'Langkah sederhana menjaga desa tetap bersih dan sehat.',
    excerpt_en: 'Simple steps to keep the village clean and healthy.',
    content: 'Kebersihan lingkungan dimulai dari rumah masing-masing. Pisahkan sampah organik dan anorganik, kelola sampah dengan bijak, dan ikut serta dalam kerja bakti rutin.',
    category: 'Lingkungan',
    category_en: 'Environment',
    author: 'Admin DesaMind',
    image_url: 'https://www.bhuanajaya.desa.id/wp-content/uploads/images/sanitasi-dan-kebersihan-desa.webp',
    is_published: true,
    created_at: '2026-05-19T08:00:00.000Z',
  },
  {
    id: 'article-4',
    title: 'Inovasi Irigasi Tetes untuk Sawah Tadah Hujan',
    title_en: 'Drip Irrigation Innovation for Rainfed Rice Fields',
    excerpt: 'Petani desa sukses terapkan irigasi tetes untuk atasi musim kemarau.',
    excerpt_en: 'Village farmers successfully apply drip irrigation to overcome the dry season.',
    content: 'Menghadapi musim kemarau panjang, kelompok tani desa mulai menerapkan teknologi irigasi tetes. Sistem ini terbukti menghemat air hingga 40% dan tetap mempertahankan produktivitas panen jagung.',
    category: 'Pertanian',
    category_en: 'Agriculture',
    author: 'Kelompok Tani Makmur',
    image_url: 'https://tse4.mm.bing.net/th/id/OIP.3-EjS00M7Xmw4VjQeC60dgHaEo?rs=1&pid=ImgDetMain&o=7&rm=3',
    is_published: true,
    created_at: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'article-5',
    title: 'Potensi Wisata Alam Bukit Hijau',
    title_en: 'Natural Tourism Potential of Green Hill',
    excerpt: 'Menjelajahi keindahan tersembunyi di sudut desa kita.',
    excerpt_en: 'Exploring the hidden beauty in the corner of our village.',
    content: 'Bukit Hijau menawarkan pemandangan matahari terbit yang memukau. Pemuda karang taruna kini sedang membangun akses jalan setapak dan spot foto untuk menarik wisatawan lokal.',
    category: 'Pariwisata',
    category_en: 'Tourism',
    author: 'Karang Taruna',
    image_url: 'https://tse1.mm.bing.net/th/id/OIP.f35VjCDLW44gppvgsU4m2AHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    is_published: true,
    created_at: '2026-06-02T10:00:00.000Z',
  },
  {
    id: 'article-6',
    title: 'Resep Rahasia Keripik Singkong Renyah',
    title_en: 'Secret Recipe for Crispy Cassava Chips',
    excerpt: 'Cara membuat keripik singkong gurih dan tahan lama ala UMKM.',
    excerpt_en: 'How to make savory and long-lasting cassava chips a la SMEs.',
    content: 'Rahasianya ada pada proses perendaman menggunakan air kapur sirih selama 30 menit sebelum digoreng. Selain itu, pastikan minyak dalam kondisi sangat panas sebelum singkong dimasukkan.',
    category: 'UMKM',
    category_en: 'Business',
    author: 'Bu Sari',
    image_url: 'https://foto.kontan.co.id/JEceyZls5MKC9Jtj-lFWxluWcU0=/smart/filters:format(webp)/2025/11/14/2066028903.jpg',
    is_published: true,
    created_at: '2026-06-03T09:00:00.000Z',
  },
];

export const STATIC_TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'module-1',
    title: 'Dasar Pemasaran Digital untuk UMKM',
    description: 'Belajar memasarkan produk lewat media sosial dan marketplace.',
    category: 'Bisnis & Marketing',
    level: 'Pemula',
    duration_minutes: 90,
    image_url: img('1460925895917-afdab827c52f'),
    instructor: 'Tim DesaMind',
    lessons: [
      { title: 'Mengenal Marketing Digital', duration: 20 },
      { title: 'Membuat Konten Menarik', duration: 35 },
      { title: 'Strategi Marketplace', duration: 35 },
    ],
    rating: 4.8,
    enrolled: 45,
    is_published: true,
    created_at: '2026-05-14T08:00:00.000Z',
  },
  {
    id: 'module-2',
    title: 'Manajemen Keuangan Usaha Kecil',
    description: 'Mengelola arus kas dan pembukuan sederhana usaha.',
    category: 'Keuangan',
    level: 'Pemula',
    duration_minutes: 75,
    image_url: img('1554224155-6726b3ff858f'),
    instructor: 'Tim DesaMind',
    lessons: [
      { title: 'Pencatatan Keuangan', duration: 30 },
      { title: 'Menghitung Laba', duration: 45 },
    ],
    rating: 4.6,
    enrolled: 30,
    is_published: true,
    created_at: '2026-05-16T08:00:00.000Z',
  },
  {
    id: 'module-3',
    title: 'Bertani Organik Modern',
    description: 'Teknik pertanian organik yang ramah lingkungan dan menguntungkan.',
    category: 'Pertanian',
    level: 'Menengah',
    duration_minutes: 120,
    image_url: img('1625246333195-78d9c38ad449'),
    instructor: 'Penyuluh Pertanian',
    lessons: [
      { title: 'Pengenalan Organik', duration: 40 },
      { title: 'Pembuatan Pupuk Kompos', duration: 40 },
      { title: 'Pengendalian Hama Alami', duration: 40 },
    ],
    rating: 4.9,
    enrolled: 25,
    is_published: true,
    created_at: '2026-05-22T08:00:00.000Z',
  },
  {
    id: 'module-4',
    title: 'Membuat Kemasan Produk Menarik',
    description: 'Panduan desain dan pemilihan bahan kemasan untuk menaikkan nilai jual.',
    category: 'Bisnis & Marketing',
    level: 'Menengah',
    duration_minutes: 60,
    image_url: 'https://kemasanretail.com/wp-content/uploads/2026/03/tips-cara-membuat-desain-kemasan-menarik-unik.webp',
    instructor: 'Desainer Grafis Desa',
    lessons: [
      { title: 'Pentingnya Branding', duration: 20 },
      { title: 'Jenis Bahan Kemasan', duration: 20 },
      { title: 'Praktek Desain Label Sederhana', duration: 20 },
    ],
    rating: 4.8,
    enrolled: 42,
    is_published: true,
    created_at: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'module-5',
    title: 'Budidaya Ikan Lele Sistem Bioflok',
    description: 'Cara efisien ternak lele di lahan sempit dengan sistem bioflok.',
    category: 'Pertanian',
    level: 'Pemula',
    duration_minutes: 100,
    image_url: 'https://ilmubudidaya.com/wp-content/uploads/2018/07/bioflok3.jpg',
    instructor: 'Dinas Perikanan',
    lessons: [
      { title: 'Apa itu Bioflok?', duration: 30 },
      { title: 'Pembuatan Kolam Terpal', duration: 30 },
      { title: 'Manajemen Pakan dan Air', duration: 40 },
    ],
    rating: 4.9,
    enrolled: 65,
    is_published: true,
    created_at: '2026-06-02T13:00:00.000Z',
  },
];

export const STATIC_ACTIONS: CommunityAction[] = [
  {
    id: 'action-1',
    title: 'Kerja Bakti Bersih Sungai',
    description: 'Membersihkan sungai desa dari sampah dan eceng gondok bersama warga.',
    category: 'Lingkungan',
    location: 'Sungai Way Sekampung',
    date: '2026-06-10',
    time: '07:00',
    max_participants: 50,
    current_participants: 23,
    organizer: 'Karang Taruna',
    image_url: img('1532996122724-e3c354a0b15b'),
    status: 'open',
    created_at: '2026-05-31T08:00:00.000Z',
  },
  {
    id: 'action-2',
    title: 'Penanaman 1000 Pohon',
    description: 'Gerakan penghijauan menanam pohon di area lahan kritis desa.',
    category: 'Lingkungan',
    location: 'Bukit Desa',
    date: '2026-06-17',
    time: '08:00',
    max_participants: 100,
    current_participants: 67,
    organizer: 'Pemerintah Desa',
    image_url: img('1466692476868-aef1dfb1e735'),
    status: 'open',
    created_at: '2026-05-29T08:00:00.000Z',
  },
  {
    id: 'action-3',
    title: 'Posyandu Balita Bulanan',
    description: 'Kegiatan rutin penimbangan dan imunisasi balita.',
    category: 'Kesehatan',
    location: 'Balai Desa',
    date: '2026-06-06',
    time: '09:00',
    max_participants: 40,
    current_participants: 40,
    organizer: 'Kader Posyandu',
    image_url: img('1576091160399-112ba8d25d1d'),
    status: 'full',
    created_at: '2026-05-26T08:00:00.000Z',
  },
  {
    id: 'action-4',
    title: 'Perbaikan Saluran Irigasi Tersumbat',
    description: 'Gotong royong membersihkan lumpur dan sampah di saluran irigasi utama sawah.',
    category: 'Infrastruktur',
    location: 'Saluran Irigasi Blok C',
    date: '2026-06-12',
    time: '07:30',
    max_participants: 60,
    current_participants: 45,
    organizer: 'Kelompok Tani',
    image_url: aiImg('farmers cleaning mud and garbage from irrigation canal rural'),
    status: 'open',
    created_at: '2026-06-02T08:00:00.000Z',
  },
  {
    id: 'action-5',
    title: 'Pengecatan Gapura Desa',
    description: 'Kegiatan mengecat ulang gapura batas desa menyambut Hari Kemerdekaan.',
    category: 'Sosial',
    location: 'Gapura Batas Desa',
    date: '2026-07-01',
    time: '08:00',
    max_participants: 20,
    current_participants: 8,
    organizer: 'Karang Taruna',
    image_url: aiImg('people painting a village entrance gate rural indonesia'),
    status: 'open',
    created_at: '2026-06-03T08:00:00.000Z',
  },
];

export const STATIC_ACTION_PARTICIPANTS = [
  { id: 'participant-1', action_id: 'action-1', user_id: 'user-1', name: 'Nina Rahma', email: 'nina@example.com', created_at: '2026-06-01T08:00:00.000Z' },
  { id: 'participant-2', action_id: 'action-1', user_id: 'user-2', name: 'Agus Salim', email: 'agus@example.com', created_at: '2026-06-01T09:00:00.000Z' },
  { id: 'participant-3', action_id: 'action-2', user_id: 'user-3', name: 'Laila Fitri', email: 'laila@example.com', created_at: '2026-06-02T10:00:00.000Z' },
];

export const STATIC_ANNOUNCEMENTS: Announcement[] = [
  { id: 'ann-1', title: 'Jadwal Pelayanan Administrasi Desa', category: 'Pemerintahan', content: 'Pelayanan administrasi desa buka Senin-Kamis 08:00-15:00 WIB dan Jumat 08:00-11:30 WIB.', date: '2026-06-01T08:00:00.000Z', is_important: true },
  { id: 'ann-2', title: 'Pembagian BLT Dana Desa Tahap II', category: 'Sosial', content: 'Pembagian BLT Dana Desa tahap II akan dilaksanakan pada tanggal 10 bulan ini di Balai Desa. Mohon membawa KTP dan KK asli.', date: '2026-05-30T08:00:00.000Z', is_important: true },
  { id: 'ann-3', title: 'Vaksinasi Hewan Ternak Gratis', category: 'Kesehatan', content: 'Dinas Peternakan mengadakan vaksinasi gratis untuk hewan ternak warga. Daftar di kantor desa.', date: '2026-05-28T08:00:00.000Z', is_important: false },
  { id: 'ann-4', title: 'Peringatan Dini Cuaca Ekstrem', category: 'Peringatan', content: 'BMKG memprakirakan hujan lebat disertai angin kencang dalam 3 hari ke depan. Warga diimbau waspada.', date: '2026-06-03T08:00:00.000Z', is_important: true },
  { id: 'ann-5', title: 'Pendaftaran Lomba Desa Bersih', category: 'Sosial', content: 'Pendaftaran lomba kebersihan antar RT telah dibuka. Hadiah jutaan rupiah menanti lingkungan terbersih.', date: '2026-06-02T08:00:00.000Z', is_important: false },
  { id: 'ann-6', title: 'Pemadaman Listrik Bergilir', category: 'Infrastruktur', content: 'Sehubungan dengan perbaikan gardu, akan dilakukan pemadaman listrik besok pukul 09:00 - 14:00 WIB.', date: '2026-06-01T08:00:00.000Z', is_important: true },
];

export const STATIC_GALLERY: GalleryItem[] = [
  { id: 'gallery-1', title: 'Kerja Bakti Mingguan', category: 'Kerja Bakti', date: '2026-05-27', image_url: 'https://1.bp.blogspot.com/-v_qFB1bi5BU/Xm9V5p4N55I/AAAAAAAAJQk/dU1eu53A_Lc0AzKsbA1ooxq2M2PSH5W_wCLcBGAsYHQ/s1600/kerja%2Bbakti.jpg' },
  { id: 'gallery-2', title: 'Kegiatan PKK', category: 'PKK', date: '2026-05-20', image_url: 'https://jatengprov.go.id/wp-content/uploads/2018/03/DOE_9041A.jpg' },
  { id: 'gallery-3', title: 'Posyandu Balita', category: 'Posyandu', date: '2026-05-13', image_url: 'https://blog.pengajartekno.co.id/wp-content/uploads/2023/08/Gambar-Posyandu-13.jpg' },
  { id: 'gallery-4', title: 'Latihan Karang Taruna', category: 'Karang Taruna', date: '2026-05-06', image_url: 'https://th.bing.com/th/id/OIP.5gdLSKeaW5T6m6TnrHprwgHaFj?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3' },
  { id: 'gallery-5', title: 'Panen Raya Padi', category: 'Pertanian', date: '2026-05-30', image_url: 'https://cdn.antarafoto.com/cache/1200x797/2020/07/28/panen-raya-padi-qkeq-dom.jpg' },
  { id: 'gallery-6', title: 'Lomba Masak PKK', category: 'PKK', date: '2026-06-01', image_url: 'https://tse4.mm.bing.net/th/id/OIP.aK3gf_1gTF9oYfR8H7wD5AHaEK?rs=1&pid=ImgDetMain&o=7&rm=3' },
  { id: 'gallery-7', title: 'Penyuluhan Kesehatan Anak', category: 'Kesehatan', date: '2026-06-02', image_url: 'https://tse2.mm.bing.net/th/id/OIP.-Me5IIVZNAkdEe36DxWhmwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3' },
  { id: 'gallery-8', title: 'Pasar Malam Desa', category: 'Budaya', date: '2026-06-03', image_url: 'https://www.bumione.com/wp-content/uploads/2024/05/Screenshot_2024_0510_183536.png' },
];

export const STATIC_PROJECTS: Project[] = [
  {
    id: 'project-1',
    title: 'Pembangunan Jalan Desa',
    description: 'Pengaspalan jalan utama desa sepanjang 2 km.',
    budget: 350000000,
    spent: 210000000,
    progress: 60,
    status: 'ongoing',
    category: 'Infrastruktur',
    image_url: img('1503387762-592deb58ef4e'),
    start_date: '2026-04-04',
    end_date: '2026-07-03',
    contractor: 'CV Karya Bangun',
    created_at: '2026-04-04T08:00:00.000Z',
  },
  {
    id: 'project-2',
    title: 'Renovasi Balai Desa',
    description: 'Perbaikan dan perluasan gedung balai desa.',
    budget: 150000000,
    spent: 150000000,
    progress: 100,
    status: 'completed',
    category: 'Infrastruktur',
    image_url: img('1486406146926-c627a92ad1ab'),
    start_date: '2026-02-03',
    end_date: '2026-05-14',
    contractor: 'CV Maju Jaya',
    created_at: '2026-02-03T08:00:00.000Z',
  },
  {
    id: 'project-3',
    title: 'Pengadaan Air Bersih',
    description: 'Instalasi sumur bor dan pipa distribusi air bersih.',
    budget: 200000000,
    spent: 50000000,
    progress: 25,
    status: 'ongoing',
    category: 'Kesehatan',
    image_url: img('1538300342682-cf57afb97285'),
    start_date: '2026-05-04',
    end_date: '2026-08-02',
    contractor: 'PT Tirta Sehat',
    created_at: '2026-05-04T08:00:00.000Z',
  },
  {
    id: 'project-4',
    title: 'Pemasangan PJU Tenaga Surya',
    description: 'Instalasi 50 titik Lampu Penerangan Jalan Umum bertenaga surya.',
    budget: 120000000,
    spent: 0,
    progress: 0,
    status: 'planning',
    category: 'Infrastruktur',
    image_url: aiImg('solar powered street light installation rural road'),
    start_date: '2026-08-01',
    end_date: '2026-09-15',
    contractor: 'PT Surya Gemilang',
    created_at: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'project-5',
    title: 'Pembangunan Saluran Drainase',
    description: 'Pembuatan saluran air sepanjang 500 meter untuk mencegah banjir genangan.',
    budget: 85000000,
    spent: 80000000,
    progress: 95,
    status: 'ongoing',
    category: 'Lingkungan',
    image_url: aiImg('construction of concrete drainage canal ditch beside rural road'),
    start_date: '2026-05-01',
    end_date: '2026-06-15',
    contractor: 'CV Karya Bangun',
    created_at: '2026-05-01T08:00:00.000Z',
  },
];

export const STATIC_APB_DESA: APBDesa = {
  year: 2026,
  total_budget: 1500000000,
  realized: 920000000,
  allocations: [
    { category: 'Pembangunan', amount: 600000000, color: '#2E6B5E' },
    { category: 'Pemberdayaan', amount: 350000000, color: '#E8B04B' },
    { category: 'Pemerintahan', amount: 300000000, color: '#3B82F6' },
    { category: 'Pembinaan', amount: 150000000, color: '#A855F7' },
    { category: 'Tak Terduga', amount: 100000000, color: '#EF4444' },
  ],
  programs: [
    { name: 'Pembangunan Jalan Desa', category: 'Pembangunan', budget: 350000000, status: 'Berjalan' },
    { name: 'Renovasi Balai Desa', category: 'Pembangunan', budget: 150000000, status: 'Selesai' },
    { name: 'Pelatihan UMKM', category: 'Pemberdayaan', budget: 100000000, status: 'Berjalan' },
    { name: 'Posyandu & Kesehatan', category: 'Pembinaan', budget: 80000000, status: 'Berjalan' },
    { name: 'Pengadaan Air Bersih', category: 'Pembangunan', budget: 200000000, status: 'Berjalan' },
  ],
};

export const STATIC_USERS: AuthUser[] = [
  {
    id: 'demo-admin',
    email: 'admin@desamind.id',
    name: 'Admin DesaMind',
    role: 'admin',
    status: 'active',
    avatar: 'AD',
    created_at: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'demo-warga',
    email: 'warga@desamind.id',
    name: 'Warga Demo',
    role: 'warga',
    status: 'active',
    avatar: 'WD',
    created_at: '2026-02-01T08:00:00.000Z',
  },
];

export const STATIC_HEALTH_SCORE: HealthScore = {
  overall: 78,
  grade: 'Baik',
  metrics: {
    cleanliness: 72,
    infrastructure: 70,
    safety: 80,
    health: 82,
    economy: 76,
    community: 88,
  },
  trend: 'naik',
  ai_narrative: 'Kondisi desa berada pada kategori baik. Prioritas terdekat adalah percepatan penyelesaian laporan infrastruktur dan menjaga ritme kegiatan warga.',
  last_updated: '2026-06-03T08:00:00.000Z',
  source_stats: {
    reports: { total: 5, pending: 2, in_progress: 2, completed: 1 },
    projects: { total: 3, average_progress: 62 },
    community: { actions: 3, participants: 130 },
    economy: { active_stores: 3, paid_orders: 2, active_jobs: 3 },
    emergency: { active: 0, resolved: 4 },
  },
};

export const STATIC_PREDICTIONS: AIPrediction[] = [
  {
    id: 'pred-1',
    category: 'Infrastruktur',
    risk_level: 'Sedang',
    confidence: 78,
    title: 'Perbaikan Jalan Perlu Diprioritaskan',
    description: 'Beberapa laporan infrastruktur masih aktif dan berpotensi mengganggu mobilitas warga.',
    recommendation: 'Jadwalkan survei teknis dan alokasikan perbaikan sementara pada titik jalan yang paling sering dilalui.',
    icon: '!',
  },
  {
    id: 'pred-2',
    category: 'Lingkungan',
    risk_level: 'Rendah',
    confidence: 68,
    title: 'Kebersihan Lingkungan Stabil',
    description: 'Kegiatan warga dan pengangkutan sampah tambahan membantu menjaga kondisi lingkungan.',
    recommendation: 'Pertahankan jadwal kerja bakti dan tambahkan edukasi pemilahan sampah rumah tangga.',
    icon: '*',
  },
  {
    id: 'pred-3',
    category: 'Ekonomi',
    risk_level: 'Rendah',
    confidence: 72,
    title: 'UMKM Lokal Menunjukkan Aktivitas Baik',
    description: 'Produk unggulan dan toko aktif memberi sinyal ekonomi lokal yang sehat.',
    recommendation: 'Dorong pelatihan pemasaran digital dan foto produk untuk memperluas jangkauan pembeli.',
    icon: '$',
  },
];

export const STATIC_DASHBOARD_STATS: DashboardStats = {
  totalReports: STATIC_REPORTS.length,
  pendingReports: STATIC_REPORTS.filter((report) => report.status === 'pending').length,
  inProgressReports: STATIC_REPORTS.filter((report) => report.status === 'in_progress').length,
  completedReports: STATIC_REPORTS.filter((report) => report.status === 'completed').length,
  resolutionRate: 20,
  activeUMKM: STATIC_STORES.length,
  totalCitizens: 1284,
  categoryData: [
    { category: 'Infrastruktur', count: 1 },
    { category: 'Sampah', count: 1 },
    { category: 'Keamanan', count: 1 },
    { category: 'Lingkungan', count: 1 },
    { category: 'Kesehatan', count: 1 },
  ],
  trendData: [
    { month: 'Jan', laporan: 5, selesai: 3 },
    { month: 'Feb', laporan: 8, selesai: 5 },
    { month: 'Mar', laporan: 10, selesai: 7 },
    { month: 'Apr', laporan: 7, selesai: 6 },
    { month: 'Mei', laporan: 12, selesai: 8 },
    { month: 'Jun', laporan: 5, selesai: 1 },
  ],
};

export const STATIC_UMKM_STATS = {
  activeStores: STATIC_STORES.length,
  verifiedStores: STATIC_STORES.length,
  soldProducts: STATIC_PRODUCTS.reduce((sum, product) => sum + Number(product.sales_count ?? 0), 0),
  averageRating: 4.8,
  reviewsCount: STATIC_PRODUCTS.reduce((sum, product) => sum + Number(product.reviews_count ?? 0), 0),
};

export const STATIC_TABLES: Record<string, unknown[]> = {
  reports: STATIC_REPORTS,
  products: STATIC_PRODUCTS,
  stores: STATIC_STORES,
  jobs: STATIC_JOBS,
  articles: STATIC_ARTICLES,
  training_modules: STATIC_TRAINING_MODULES,
  community_actions: STATIC_ACTIONS,
  announcements: STATIC_ANNOUNCEMENTS,
  gallery: STATIC_GALLERY,
  projects: STATIC_PROJECTS,
  users: STATIC_USERS,
};
